import {StyleSheet} from 'react-native';
import {Metrics, Colors} from '../../Themes';
export default StyleSheet.create({
  item: {
    height: 80,
    //marginVertical: 5,
    //borderRadius: Metrics.textInBr,
    borderBottomWidth: 1,
    borderColor: '#A2A1A2',
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    //backgroundColor: Colors.soft,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
  },
  image: {
    width: Metrics.images.medium,
    height: Metrics.images.medium,
    borderWidth: 4,
    borderColor: '#43B9E3',
    borderRadius: Metrics.images.medium / 2,
  },
  textContainer: {
    marginHorizontal: 10,
  },

  iconsContainer: {
    flex: 1,
    height: 60,
    justifyContent: 'flex-end',
    alignItems: 'center',
    flexDirection: 'row',
  },
  iconsItem: {
    width: 25,
    marginHorizontal: 5,
    padding: 5,
    borderRadius: 15,
    backgroundColor: '#43B9E3',
    alignItems: 'center' 
  },
  modalView: {
    width: 300, 
    height: 450, 
    backgroundColor: '#fff', 
    alignSelf: 'center', 
    marginTop: 50, 
    borderRadius: 5, 
    elevation: 10, 
    shadowColor: '#000000', 
    //paddingBottom: 40,
    //paddingHorizontal: 10,
    //backgroundColor: '#76285C',
    shadowColor: '#000',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 1,
  },
  btnCerrar: {
    //margin:5,
    position: 'absolute',
    top: 10,
    right: 10,
    padding: 5,
    borderRadius: 15,
    backgroundColor: '#fff',
    width: 25,
    alignItems: 'center'
  },
  imagenModal: {
    width: '100%', 
    height: '100%',
    borderRadius: 5,
    // shadowColor: '#000',
    // shadowOffset: { width: 5, height: 5 },
    // shadowOpacity: 0.8,
    // shadowRadius: 5,
    // elevation: 1,
  },
  panelModal: {
    backgroundColor: 'rgba(0,0,0,0.5)',
    position: 'absolute',
    height: 30,
    justifyContent: 'center', 
    bottom: 0,
    left: 0,
    right: 0, 
  }
});
