import {Metrics, Colors} from '../../Themes';

export default {
  container: {
    flex: 1,
    width: Metrics.screenWidth,
    height: Metrics.screenHeight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentList: {
    flex: 1,
    width: Metrics.screenWidth,
  },
  loading: {
    backgroundColor: Colors.accentMask(0.5),
    position: 'absolute',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: Metrics.screenHeight,
    width: Metrics.screenWidth,
    zIndex: 2000,
  },
  footer:{
    height: 40,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0, 
    backgroundColor: '#44123A',
    alignItems: 'center',
  },
  textfooter:{
    color: '#fff',
    marginTop: 11,
    fontSize: 15,
    //borderBottomColor: '#fff'
    //textDecorationLine: 'underline', 
  },
  modalView: {
    flex: 1,
    //marginTop: 0,
    backgroundColor: '#fff', 
    alignSelf: 'center', 
    //marginTop: 50, 
    borderRadius: 5, 
    elevation: 10, 
    shadowColor: '#000000', 
    //paddingBottom: 40,
    //paddingHorizontal: 10,
    //backgroundColor: '#76285C',
    shadowColor: '#000',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.8,
    shadowRadius: 5,
    elevation: 1,
  },
  btnCerrar: {
    //margin:5,
    position: 'absolute',
    top: 40,
    left: 10,
    padding: 5,
    borderRadius: 15,
    //backgroundColor: '#fff',
    width: 25,
    alignItems: 'center' 
  },
};
